name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  stylua:
    name: Check Lua formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }} 
          args: --check .
