name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  stylua:
    name: Check Lua formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }} 
          args: --check .

  docs:
    name: Generate Vim docs
    runs-on: ubuntu-latest
    needs: stylua
    steps:
      - uses: actions/checkout@v5
      - name: Generate Vim help docs
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: monokai-v2
          version: "Neovim >= 0.10.0"
          demojify: true
          treesitter: true
      - name: Commit docs
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(build): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
