name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          package-name: monokai-v2.nvim
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          token: ${{ secrets.GITHUB_TOKEN }}
